// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUMc1obeQo_H46DUlUXZ5pRL-0HcGJTd0',
    appId: '1:548779303081:web:3d77ea908bc321dc2789b8',
    messagingSenderId: '548779303081',
    projectId: 'todolistapp-db539',
    authDomain: 'todolistapp-db539.firebaseapp.com',
    storageBucket: 'todolistapp-db539.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp0jezJ-4mJjV21QT0XBkoltV9IEdnsR8',
    appId: '1:548779303081:android:e299bfd6d7c6ad052789b8',
    messagingSenderId: '548779303081',
    projectId: 'todolistapp-db539',
    storageBucket: 'todolistapp-db539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXq1md3qV89en-RxK5rXV35E5japBRo8',
    appId: '1:548779303081:ios:9410cef085b092592789b8',
    messagingSenderId: '548779303081',
    projectId: 'todolistapp-db539',
    storageBucket: 'todolistapp-db539.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJXq1md3qV89en-RxK5rXV35E5japBRo8',
    appId: '1:548779303081:ios:9410cef085b092592789b8',
    messagingSenderId: '548779303081',
    projectId: 'todolistapp-db539',
    storageBucket: 'todolistapp-db539.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUMc1obeQo_H46DUlUXZ5pRL-0HcGJTd0',
    appId: '1:548779303081:web:8f5f09ce1c0b045b2789b8',
    messagingSenderId: '548779303081',
    projectId: 'todolistapp-db539',
    authDomain: 'todolistapp-db539.firebaseapp.com',
    storageBucket: 'todolistapp-db539.firebasestorage.app',
  );
}
